name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Build
      run: |
        npm install
        npm run build

    - name: Commit build artifacts
      run: |
        git config --global user.name "Continuous integration"
        git config --global user.email "mseiderer@users.noreply.github.com"
        git commit -a -m "CI build"
        git push
